name: List Files and Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  list-and-build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List all files
        run: |
          find . -type f

      - name: Replace UIWebView with WKWebView and import WebKit
        run: |
          find . -name "*.m" -type f -print0 | xargs -0 sed -i '' 's/UIWebView/WKWebView/g'
          find . -name "*.h" -type f -print0 | xargs -0 sed -i '' 's/UIWebView/WKWebView/g'
          find . -name "*.m" -type f -exec sh -c 'grep -q "#import <WebKit/WebKit.h>" "$0" || sed -i "" "1i#import <WebKit/WebKit.h>" "$0"' {} \;

      - name: Update UIApplication usage for Mac Catalyst
        run: |
          find . -name "*.m" -type f -print0 | xargs -0 sed -i '' 's/UIApplication\.shared/[UIApplication sharedApplication]/g'
          find . -name "*.m" -type f -print0 | xargs -0 sed -i '' 's/\.windows\.first(where: { \$0\.isKeyWindow })/\.windows\.firstObject/g'

      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default

      - name: Build
        env:
          scheme: ${{ 'default' }}
        run: |
          if [ $scheme = default ]; then scheme=$(cat default); fi
          file_to_build=$(ls -1 | grep -Ei '\.xcworkspace$|\.xcodeproj$' | head -n 1)
          if [[ $file_to_build == *.xcworkspace ]]; then filetype_parameter="workspace"; else filetype_parameter="project"; fi
          xcodebuild clean build analyze -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination 'platform=macOS,arch=arm64' | xcpretty && exit ${PIPESTATUS[0]}
